spring:
  profiles:
    active: local
  #redis관련 설정
  redis:
    host: localhost #redis가 설치된 서버 호스트
    port: 6379  #redis가 설치된 서버 포트
  datasource:
    url: jdbc:mysql://localhost:3306/friends
    username: octopusUser
    password: octopusUser
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #spring security 비활성화
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration